# Base da imagem Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto para o contêiner
COPY . /app

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta usada pela aplicação
EXPOSE 8080

# Comando para executar a aplicação
CMD ["python", "app.py"]
